apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-csv
spec:
  suspend: true
  schedule: {{ .Values.archiveJob.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: archive
              image: {{ .Values.archiveJob.repository }}:{{ .Values.archiveJob.tag }}
              imagePullPolicy: Always
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: password
                      key: postgres
          restartPolicy: Never