apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.repository }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.web.pullPolicy }}
          ports:
            - containerPort: 80