apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3
spec:
  serviceName: s3
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      initContainers:
      - name: bucket-init
        image: minio/mc:latest
        restartPolicy: Always
        command: ["/bin/sh", "/scripts/init.sh"]
        env:
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password
                key: minio
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      containers:
      - name: s3
        image: minio/minio:latest
        args:
          - server
          - /data
        ports:
        - containerPort: 9000
          name: tcp
        env:
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password
                key: minio
        volumeMounts:
        - name: vol
          mountPath: /data
      volumes:
        - name: scripts
          configMap:
            name: s3-init
            defaultMode: 0755

  volumeClaimTemplates:
  - metadata:
      name: vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi